=== RohaTechShow/IntegrativeProgramming/XML Lab examples/LAB2 - DTD LAB/catalog xml/contacts.dtd
<!ELEMENT contacts (contact*) >
<!ATTLIST contacts version CDATA #FIXED "1.0">
<!ATTLIST contacts source CDATA #IMPLIED>
<!ELEMENT contact (name, location, phone, knows, description, website+, email)>
<!ATTLIST contact person ID #REQUIRED>
<!ATTLIST contact GENDER (M|F) "F">
<!ELEMENT name (first+, middle?, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT location (address | (latitude, longitude))*>
<!ELEMENT address (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone kind (Home | Work | Cell | Fax) "Home">
<!ELEMENT knows EMPTY>
<!ELEMENT description (#PCDATA | em | strong | br)*>
<!ELEMENT em (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT br EMPTY>
<!ELEMENT website (#PCDATA) >
<!ELEMENT email (#PCDATA) >

=== RohaTechShow/IntegrativeProgramming/XML Lab examples/LAB2 - DTD LAB/catalog xml/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacts SYSTEM "contacts.dtd" >
<contacts version="1.0" source="source data">
   <contact person="ID52652623" GENDER="F">
      <name>
          <first>Wobetu</first>
          <middle>Shiferaw</middle>
          <last>Asmare</last>
      </name>
      <location>
          <address>Debre Markos</address>
      </location>
      <phone kind="Cell">+2517878465</phone>
      <knows/>
      <description></description>
      <website>wobie.com</website>
      <email>wobieatdmu.com</email>
   </contact>
   
    <contact person="ID526526" GENDER="M">
      <name>
          <first>Alemu</first>
          <middle>Ashagrie</middle>
          <last>Tesema</last>
      </name>
      <location>
          <address>Debre Markos</address>
      </location>
      <phone kind="Cell">+2517878</phone>
      <knows/>
      <description></description>
      <website>alex.com</website>
      <email>alexisatgmail.com</email>
   </contact>
</contacts>
