<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CATALOG [

<!ENTITY AUTHOR "John Doe">
<!ENTITY COMPANY "JD Power Tools, Inc.">
<!ENTITY EMAIL "jd@jd-tools.com">

<!ELEMENT CATALOG (PRODUCT+)>

<!ELEMENT PRODUCT
(SPECIFICATIONS+,OPTIONS?,PRICE*,NOTES?)>
<!ATTLIST PRODUCT
NAME CDATA #REQUIRED
CATEGORY (HandTool|Table|Shop-Professional) "HandTool"
PARTNUM CDATA #IMPLIED
PLANT (Pittsburgh|Milwaukee|Chicago) "Chicago"
INVENTORY (InStock|Backordered|Discontinued) "InStock">

<!ELEMENT SPECIFICATIONS (#PCDATA)>
<!ATTLIST SPECIFICATIONS
WEIGHT CDATA #IMPLIED
POWER CDATA #IMPLIED>

<!ELEMENT OPTIONS (#PCDATA)>
<!ATTLIST OPTIONS
FINISH (Metal|Polished|Matte) "Matte"
ADAPTER (Included|Optional|NotApplicable) "Included"
CASE (HardShell|Soft|NotApplicable) "HardShell">

<!ELEMENT PRICE (#PCDATA)>
<!ATTLIST PRICE
MSRP CDATA #IMPLIED
WHOLESALE CDATA #IMPLIED
STREET CDATA #IMPLIED
SHIPPING CDATA #IMPLIED>

<!ELEMENT NOTES (#PCDATA)>
]>


<CATALOG>
  <PRODUCT NAME="" CATEGORY="HandTool" PARTNUM="purtinm data" PLANT="Pittsburgh" INVENTORY="InStock">
        <SPECIFICATIONS WEIGHT="4353" POWER="2344">This is spec content</SPECIFICATIONS>
        <OPTIONS FINISH="Polished">This is options content</OPTIONS>
        <NOTES>
              &AUTHOR;  &COMPANY;    &EMAIL;
        This is notes section</NOTES>
  </PRODUCT>

<PRODUCT NAME="" CATEGORY="HandTool" PARTNUM="purtinm data" PLANT="Pittsburgh" INVENTORY="InStock">
        <SPECIFICATIONS WEIGHT="4353" POWER="2344">This is spec content</SPECIFICATIONS>
        <OPTIONS FINISH="Polished">This is options content</OPTIONS>
        <NOTES>
              &AUTHOR;  &COMPANY;    &EMAIL;
        This is notes section</NOTES>
  </PRODUCT>

</CATALOG>
  
